class Objetos {
lista = {
    finales: [
        "Detracción celestial",
        "Tejesueños",
        "Perforaplanos de Zaz'Zak",
        "Trineo del solsticio",
        "Tonada sanguina",
        "Botas sibióticas",
        "Botas jonias de la lucidez",
        ""
        ],
    Iniciales: [
        "Poción de vida",
        "Poción reutilizable",
        "Amuleto de las hadas",
        "Daga",
        "Mota brillante",
        "Botas",
        "Perla de rejuvenecimiento",
        "Cristal de zafiro",
        "Armadura de tela",
        "Espada larga",
        "Sello oscuro",
        "Cristal de rubí",
        "Manto de anulación de magia",
        "Tomo ampliación",
        "Anillo de Doran",
        "Lágrima de la diosa",
        "Atlas mundial",
        "Escudo de Doran",
        "Espada de Doran",
        "Preferencia",
        "Cachorro de Garra ígnea",
        "Cría de Caminabrisas",
        "Brote de Brincamontes",
        "Elixir de hierro",
        "Elixir de brujería",
        "Elixir de cólera",
        "Capa de agilidad",
        "Ídolo prohibido",
        "Honda de explorador",
        "Arco curvo",
        "Réctrice",
        "Chaleco de cadenas",
        "Armadura lunar alada",
        "Gema avivadora",
        "Chaleco de zarzas",
        "Llamada del verdugo",
        "Brazal cristalino",
        "Orbe del olvido",
        "Vara explosiva",
        "Capa negatrón",
        "Códice diabólico",
        "Pico",
        "Cinturón de gigante",
        "Cetro vampírico",
        "Cenizas predestinadas",
        "Broquel glacial",
        "Brillo",
        "Brisa de éter",
        "Espejo de cristal de Bandle",
    ],
    Wards: [
        "Guardián de control",
        "Guardián invisible",
        "Visión lejana modificada",
        "Lente del oráculo",
    ]
};
}
