class Objetos {
lista = {
    finales: {
        "Detracción celestial": {
            "tipo": "objeto",
            "unica": "apoyo"
        },
        "Tejesueños": {
            "tipo": "objeto",
            "unica": "apoyo"
        },
        "Perforaplanos de Zaz'Zak":{
            "tipo": "objeto",
            "unica": "apoyo"
        },
        "Trineo del solsticio":{
            "tipo": "objeto",
            "unica": "apoyo"
        },
        "Tonada sanguina":{
            "tipo": "objeto",
            "unica": "apoyo"
        },
        "Botas sibióticas":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas jonias de la lucidez":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas de rapidez":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Grebas de berserker":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas de hechicero":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas blindadas":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas de mercurio":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Robaalmas de Mejai":{
            "tipo": "objeto",
            "unica": "no"
        },
        "Lucidez carmesí":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Avance eterno":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Marcha veloz":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Grebas de metal":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Botas del lanzahechizos":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Avance blindado":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Trituradoras encadenadas":{
            "tipo": "objeto/botas",
            "unica": "no"
        },
        "Canción de batalla de Shurelya":{
            "tipo": "objeto",
            "unica": "no"
        },
        "Convergencia de Zeke",
        "Medallón de los Solari de Hierro",
        "Incensario ardiente",
        "Renovación de piedra lunar",
        "Ecos de Helia",
        "Mandato imperial",
        "Bastón de aguas fluidas",
        "Redención",
        "Promesa de caballero",
        "Bendición de Mikael",
        "Piedra de visión vigilante",
        "Marcasendas",
        "Llegada del invierno",
        "Malla de espinas",
        "Corazón de hielo",
        "Núcleo albar",
        "Colmillo de serpiente",
        "Cetro de cristal de Rylai",
        "Cintomisil hextech",
        "Guja sombría",
        "Vara de las edades",
        "Bailarín espectral",
        "Huracán de Runaan",
        "Cañón de fuego rápido",
        "Filofugaz de Navori",
        "Máscara abisal",
        "Rostro espiritual",
        "Égida de fuego solar",
        "Puñal de Statikk",
        "Malignidad",
        "Presagio de Randuin",
        "Precisión infalible",
        "Oportunidades",
        "Desesperanza eterna",
        "Antorcha de fuego negro",
        "Final del ingenio",
        "Filo fantasmal de Youmuu",
        "Fuerza de la naturaleza",
        "Fulgor vano",
        "Florescecia sepulcral",
        "Compañera de Luden",
        "Rookern kaénico",
        "Bastón del arcángel",
        "Manamune",
        "Segador de esencia",
        "Coraza del muerto",
        "Sobrecarga tormentosa",
        "Guantelete de hielo",
        "Eclipse",
        "Maldición sanguinolenta",
        "Renovación de piedra lunar",
        "Morellonomicón",
        "Soberbia",
        "Flechas de los Yun Tal",
        "Cuchilla negra",
        "Experimento de hexarmadura",
        "Corazón de acero",
        "Velo del hada de la muerte",
        "Diente de Nashor",
        "Hoja de furia de Guinsoo",
        "Bastón del vacío",
        "Rompecascos",
        "El final",
        "Filo de la noche",
        "Impulso cósmico",
        "Tormento de Liandry",
        "Arcoescudo inmortal",
        "Recaudadora",
        "Rencor de Seryida",
        "Arco axiomáico",
        "Soberbia",
        "Espada ciclovoltaica",
        "Recuerdos de lord Dominik",
        "Armadura de Warmog",
        "Fauces de Malmortius",
        "Lanza de Shojin",
        "Creagrietas",
        "Mecanoespada punki",
        "Firmamento desgarrado",
        "Verdugo de krakens",
        "Ángel de la guarda",
        "Calibrador de Sterak",
        "Perdición del liche",
        "Cimitarra mercurial",
        "Hoja del rey arruinado",
        "Llamasombría",
        "Jak'Sho el Proteico",
        "Hidra profana",
        "Reloj de arena de Zhonya",
        "Sangría del soberano",
        "Recordatorio letal",
        "Hidra voraz",
        "Hidra titánica",
        "Baile de la muerte",
        "Cortasendas",
        "Fuerza de trinidad",
        "Sanguinaria",
        "Filo infinito",
        "Sombrero mortal de Rabadon",
    },
    Iniciales: [
        "Poción de vida",
        "Poción reutilizable",
        "Amuleto de las hadas",
        "Daga",
        "Mota brillante",
        "Botas",
        "Perla de rejuvenecimiento",
        "Cristal de zafiro",
        "Armadura de tela",
        "Espada larga",
        "Sello oscuro",
        "Cristal de rubí",
        "Manto de anulación de magia",
        "Tomo ampliación",
        "Anillo de Doran",
        "Lágrima de la diosa",
        "Atlas mundial",
        "Escudo de Doran",
        "Espada de Doran",
        "Preferencia",
        "Cachorro de Garra ígnea",
        "Cría de Caminabrisas",
        "Brote de Brincamontes",
        "Elixir de hierro",
        "Elixir de brujería",
        "Elixir de cólera",
        "Capa de agilidad",
        "Ídolo prohibido",
        "Honda de explorador",
        "Arco curvo",
        "Réctrice",
        "Chaleco de cadenas",
        "Armadura lunar alada",
        "Gema avivadora",
        "Chaleco de zarzas",
        "Llamada del verdugo",
        "Brazal cristalino",
        "Orbe del olvido",
        "Vara explosiva",
        "Capa negatrón",
        "Códice diabólico",
        "Pico",
        "Cinturón de gigante",
        "Cetro vampírico",
        "Cenizas predestinadas",
        "Broquel glacial",
        "Brillo",
        "Brisa de éter",
        "Espejo de cristal de Bandle",
        "Rescoldo de Bami",
        "Cuerno del guardián",
        "Orbe del guardián",
        "Espada del guardián",
        "Martillo del guardián",
        "Malla del guardián",
        "Daga dentada",
        "Martillo de guerra de Caulfield",
        "Sello de acero",
        "Bacteriófago",
        "Protección de la legión",
        "Alternador de hextech",
        "Joya de la plaga",
        "Piedra de guardianes atenta",
        "Tuneladora",
        "Vara innecesariamente grande",
        "Hacha hogareña",
        "Tiamat",
        "Fervor",
        "Capítulo perdido",
        "Hábito del espectro",
        "Espadón",
        "Fajín de mercurio",
        "Disfraz encantado",
        "Sorbemaleficios",
        "Catalizador de eones",
        "Carcaj del mediodía",
        "Embrutecedor",
        "Últimas palabras",
        "Brazalete de la buscadora",
        "Barrera frondosa",

    ],
    Wards: [
        "Guardián de control",
        "Guardián invisible",
        "Visión lejana modificada",
        "Lente del oráculo",
    ]
};
}
